/// Flutter icons LodgifyIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LodgifyIcons
///      fonts:
///       - asset: fonts/LodgifyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LodgifyIcons {
  LodgifyIcons._();

  static const _kFontFam = 'LodgifyIcons';
  static const String? _kFontPkg = null;

  static const IconData booking_features = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData booking_ok = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_line_up = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_line_down = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
